parameters:
  - name: REPO_COUNT
    displayName: Repo Count
    type: string
    default: 200
  - name: OLD_VERSION
    displayName: Baseline typescript package version
    type: string
    default: latest
  - name: NEW_VERSION
    displayName: Candidate typescript package version
    type: string
    default: next

trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'DetectNewErrors'
  timeoutInMinutes: 360
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'
  - task: npmAuthenticate@0
    inputs:
      workingFile: './.npmrc'
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'TypeScript – Internal Services(57bfeeed-c34a-4ffd-a06b-ccff27ac91b8)'
      KeyVaultName: 'jststeam-passwords'
      SecretsFilter: 'acasey-PAT'
      RunAsPreJob: false
  - script: |
      npm ci
      npm run build
      node index ${{ parameters.REPO_COUNT }} ${{ parameters.OLD_VERSION }} ${{ parameters.NEW_VERSION }}
    env:
      GITHUB_PAT: $(acasey-PAT)