parameters:
  - name: REPO_COUNT
    displayName: Repo Count
    type: string
    default: 200
  - name: OLD_VERSION
    displayName: Baseline typescript package version
    type: string
    default: latest
  - name: NEW_VERSION
    displayName: Candidate typescript package version
    type: string
    default: next

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- task: npmAuthenticate@0
  inputs:
    workingFile: './.npmrc'
- script: |
    npm ci
    npm run build
    node index ${{ parameters.REPO_COUNT }} ${{ parameters.OLD_VERSION }} ${{ parameters.NEW_VERSION }}