pr:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 'DetectNewErrors'
  timeoutInMinutes: 360
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'
  - task: npmAuthenticate@0
    inputs:
      workingFile: './.npmrc'
  - script: |
      npm ci
      npm run build
      npm test
    env:
      GITHUB_PAT: $(TypeScriptErrorDeltas)
